### PR TITLE
Feature/landing page_enter word and display list

### PR DESCRIPTION
**Pull request by AstridOttmann**
The list is shown alphabetically sorted, the new entry always appears on top. To avoid double entries, I implemented a filter-function.

### CODE REVIEW

**Comment by RobinWitt** [comment]
Looks good to me! Is your app going to be in the English language?

**Review by RobinWitt — APPROVED** [review]
Just one suggestion: Later in development, you might think about how to describe both of the input fields so that the User knows which word he has to enter first. (his native language or the new language)

**Comment by AstridOttmann** [comment]
Thanks for your approval! 

To answer your question concerning the language of the app: 
I decided to take English because most people speak it. I plan to have a settings page, where you can choose the language in which the words should be translated. 

Regarding your second comment: 
I did not pay so much attention describing the input fields by now, because I have to change them in the next step anyway. Is that what you meant?

**Comment by RobinWitt** [comment]
Yes that's what I meant, right now it's not clear which input to use for which word, but if that is changed later anyway it does not matter.

**Pull request merged**
